### ISSUE TITLE
The difference of the preprocess between "what you see" and "second"

### ISSUE THREAD

**Issue by conan-ux** [peiyunh/wysiwyg#4]
Hi I notice that you create the groud truth with sweep info. And the code uses the sweep info to create the new ground truth box instead of the original boxes. It shows that "only use non-key frame boxes when the object is moving" in your code. I want to know why we should do this for "['vehicle.moving', 'cycle.with_rider', 'pedestrian.moving']". https://github.com/peiyunh/wysiwyg/blob/bb0f6ecbf3f15082fe4ec14a701ccbb14198babd/second/data/all_dataset.py#L187

**Comment by peiyunh** [comment]
In SECOND's implementation, when copy-pasting objects for augmentation purposes, it copy-pastes based on bounding boxes in key frames. However, the point clouds of moving objects will be truncated over non-key frames. My implementation computes object bounding boxes on non-key frames by looking up the sweep info and in turn allows for more accurate augmentation for moving objects. Does it make sense?

**Comment by conan-ux** [comment]
Oh  I see. That makes sense. Dose this modification also have effect on the evaluation judgement, since the ground truth box has been modified which is different from the ground truth in key frames?

**Comment by peiyunh** [comment]
It won't have any effect on evaluation because first we are only doing things differently with regard to non-key frames and second evaluation only cares about key frames.
