### ISSUE TITLE
the meaning of timestamp.

### ISSUE THREAD

**Issue by tianyuluan** [peiyunh/wysiwyg#5]
1: What does the time_stamp in point cloud coding mean? Does the original data set have to be continuous frames? I didn't understand this piece, I hope you can answer my doubts.
2: On our own data set, we originally used random placement targets for data enhancement. The effect is not very obvious, so I think your work is very meaningful.
3: If you want to use your method. Do I need to do something with the general point cloud (x, y, z, i)?

thank you so much!!!!!!

**Comment by peiyunh** [comment]
`time_stamp` represents the temporal offset of each 3D point. This is useful when you aggregate point clouds from multiple LIDAR scans. If you take a look at the paper, we talk about temporal aggregation, where we aggregate point clouds over the last 10 frames as the network input. At 20Hz, that means the magnitude of `time_stamp` would vary from 0 to 0.45 (second). 

Hopefully it helps.
